# 英文字のコロン(:)がある時、テキストを英文字の引用符""で囲ってください。
# 論文のリンクはない時に、urlの行を記入しない、または空欄/nullにしてください。
# 内容の前のスペース数を、必ず前文と一致にしてください。
# 必ず英語の半角スペースを使用してください。
# If the title includes English colon (:), please surround the title with quotation mark "".
# If there is no link to the paper, leave blank the url line, or fill the url line with null (no quotation mark needed)
# DO KEEP WHITESPACE COUNT CONSISTENT
# DO USE ENGLISH HALF-WIDTH spaces!
members:
  -
    name: 徳岡　大
    papers:
      -
        title: 徳岡　大・佐藤深雪・森田愛子 (2018). アルバイト場面における他者志向的動機づけが作業量の促進に及ぼす影響――実験による検討――. パーソナリティ研究, 27, 80-82.
        url: https://doi.org/10.2132/personality.27.1.7
      -
        title: 山森光陽・伊藤　崇・中本敬子・萩原康仁・徳岡　大・大内善広 (2018). 加速度計を用いた小学校の授業参観・課題従事行動の把握. 日本教育工学会論文誌, 41, 501-510.
        url: https://doi.org/10.15077/jjet.41077
      -
        title: 徳岡　大・山森光陽・萩原康仁 (2017). 学級規模と児童の学習目標志向性との関係：小学後5年生を対象として. 国立教育政策研究所.
        url: null
  -
    name: 西田若葉
    papers:
      -
        title: 西田若葉・杉村和美 (2016). 大学生におけるアイデンティティ・スタイルの特徴およびwell-beingとの関連, 青年心理学研究, 28, 17-27.
        url: https://doi.org/10.20688/jsyap.28.1_17
      -
        title: 杉村和美・畑野 快・徳岡 大・西田若葉・佐藤裕樹・保木井啓史　(2013).　日本人大学生における対人関係領域のアイデンティティにとって重要な他者は誰か？ ―選択された他者別に検討した，アイデンティティ形成の３次元と人格，心理社会的問題，親子関係との関連―　広島大学大学院教育学研究科紀要 第三部, 62, 89-97.
        url: http://doi.org/10.15027/35400
  -
    name: 日原尚吾
    papers:
      -
        title: "Hihara, S., Ishibashi, I., Umemura, T., & Sugimura, K. (2019). The roles of configurations of multiple identity domains in adaptive and maladaptive functioning in Japanese emerging adults: Using a culturally relevant index. Emerging Adulthood."
        url: https://doi.org/10.1177/2167696819858457
      -
        title: "Hihara, S., Umemura, T., & Sugimura, K. (2019). Considering the negatively formed identity: Relationships between negative identity and problematic psychosocial beliefs. Journal of Adolescence, 70, 24-32."
        url: https://doi.org/10.1016/j.adolescence.2018.11.002
      -
        title: "Hihara, S., Sugimura, K., & Syed, M. (2018). Forming a negative identity in contemporary society: Shedding light on the most problematic identity resolution. Identity, 18, 325-333."
        url: https://doi.org/10.1080/15283488.2018.1524329
  -
    name: 岩佐康弘
    papers:
      -
        title: "Iwasa, Y., Hihara, S., Umemura, T., Tazume, H., & Sugimura, K. (2021). Identity formation and school experience among university students in a teacher training program: A four-wave longitudinal study during the teaching practicum."
      -
        title: 岩佐康弘・杉村和美・田爪宏二（2019）.教員養成課程の大学生における教職を目指す過程での再考及び理想の教師像への志向性とアイデンティティ発達との関連，青年心理学研究, 31, 19-33.
  -
    name: 石橋彩波
    papers:
      -
        title: "Hihara, S., Ishibashi, I., Umemura, T., & Sugimura, K. (2019). The roles of configurations of multiple identity domains in adaptive and maladaptive functioning in Japanese emerging adults: Using a culturally relevant index. Emerging Adulthood."
        url: https://doi.org/10.1177/2167696819858457

# 英文字のコロン(:)がある時、テキストを英文字の引用符""で囲ってください。
# 論文のリンクはない時に、urlの行を記入しない、または空欄/nullにしてください。
bachelors:
  -
    title: 日本の若者のライフストーリーの構築過程におけるマスターナラティブからの逸脱―ひきこもりに着目して―
    url: https://development.hiroshima-u.ac.jp/rese/abstract/2021_yasui.pdf
  -
    title: アイデンティティ発達と社会的比較の関連
    url: https://development.hiroshima-u.ac.jp/rese/abstract/2021_ishizaki.pdf
  -
    title: ヘリコプター的養育と自己決定感及び精神的健康との関連―親子関係に対する文化的価値観の差異に着目して―
    url: https://development.hiroshima-u.ac.jp/rese/abstract/2021_sakao.pdf
  -
    title: 児童養護施設における入所児の援助要請行動―自然観察研究法を用いて―
  -
    title: 青年期の親子関係と友人関係のアタッチメント表象
    url: https://development.hiroshima-u.ac.jp/rese/abstract/2020_azuma.pdf
  -
    title: アタッチメントにおける安心の基地表象とアイデンティティの探求の関連
    url: https://development.hiroshima-u.ac.jp/rese/abstract/2020_handa.pdf
  -
    title: 青年期におけるアタッチメント対象の移行と心理的適応
    url: https://development.hiroshima-u.ac.jp/rese/abstract/2018attachment_husamune.pdf
  -
    title: アタッチメントにおける安心の基地表象とアイデンティティの探求の関連
    url: https://development.hiroshima-u.ac.jp/rese/abstract/2020_handa.pdf
  -
    title: 青年期の親子関係と友人関係のアタッチメント表象
    url: https://development.hiroshima-u.ac.jp/rese/abstract/2020_azuma.pdf
  -
    title: 自己評価と他者評価の不一致に関する捉え方と対処法がアイデンティティ発達に及ぼす影響
  -
    title: 支援者が捉える非行からの立ち直り-非行少年の内的資質と支援者の要因に着目して-
    url: https://development.hiroshima-u.ac.jp/rese/rese/abstract/hikou_taketomo2018.pdf
  -
    title: 両親・友人への過剰適応傾向とアタッチメント・ストレス反応との関連
  -
    title: 青年期におけるアタッチメント対象の移行と心理的適応
    url: https://development.hiroshima-u.ac.jp/rese/abstract/2018attachment_husamune.pdf
  -
    title: 両親間葛藤に対する子どもの態度の変化に関する探索的検討
    url: https://development.hiroshima-u.ac.jp/rese/abstract/2017maritalconflict_asai.pdf
  -
    title: 高校生の道徳不活性化傾向と学校内問題行動，自己愛との関連
  -
    title: 失恋ストレスコーピングと愛着次元の関連
  -
    title: 現代青年における友人関係の取り方と適応の関連―表面的関係・内面的関係の2側面に着目して―
  -
    title: 理想自己への志向性とBig Five特性の関連
  -
    title: 青年の結婚観および結婚不安に与える両親の不和の影響
  -
    title: 青年の否定的アイデンティティ選択過程の検討
    url: https://development.hiroshima-u.ac.jp/rese/abstract/2014negativeidentity_hihara.pdf
  # 以下は、titleしかいない時のもう一つの書き方。どちらでも大丈夫です
  - title: 大学生の読書行動に関する心理学的研究
  - title: いじめられた体験における自己成長感獲得を促進する他者からの支援の検討
  - title: 青年期の劣等感に内省への取り組み方と未来展望が与える影響
  - title: 青年の心理発達における親子関係ときょうだい関係の役割
  - title: 高校生の人物評価に及ぼす成功帰属スタイルの効果
  - title: 青年期の恋愛と性別役割意識―逆転カップルは柔軟な性別役割意識の持ち主か―
  - title: 高齢者の友人関係と主観的幸福感
  - title: 非行少年の対人的疎外感、社会的スキル、および親和動機について
  - title: 児童生徒の問題行動に関する調査研究
  - title: 主張行動スタイルが人物評価に与える影響
  - title: 友人とのつきあい方とコンピテンスの関連
  - title: 学習の失敗場面における対処方略と無気力
  - title: 関係性の観点からみた青年期のアイデンティティ
  - title: 大学生と親世代の羞恥感情の比較検討
  - title: 大学生の友人関係の親密度からみた怒りの動機と攻撃行動
  - title: 大学生の話すスキル・聞くスキルと友人関係
  - title: 学習場面と対人場面における大学生の精神的回復力に関する研究
  - title: 大学生の友人関係における自己表明と他者の表明を望む気持ち
  - title: 攻撃場面における第三者の傍観行為に対する幼児の善悪判断
  - title: 幼児の第３者的立場からの分配行動に及ぼす影響要因の検討
  - title: 大学生の職業決定に及ぼす友人の影響
  - title: 時間的信念に及ぼす影響要因の検討
  - title: 大学生の職業興味形成に関するプロセスモデルの検討
  - title: 怒り喚起から行動に至る社会的情報処理過程の検討
  - title: 青年期における自己愛と自尊感情の発達的変化
  - title: 高校教師のバーンアウトに及ぼす影響要因の検討
  - title: 児童の社会的スキルの実行に関連する要因の検討
  - title: 中学生の教師または友人に対する信頼感と学校適応感の関連
  - title: 女子大新入生に対するキャリア教育の効果
  - title: 中高生のキャリア意識と学校適応感の関連
  - title: 中学生の相談しにくい悩みに関する研究
  - title: 遅延価値割引と楽観性との関連
  - title: 科目選好別にみた中高生の学習方略と自己効力感の関連
  - title: 大学生の自己開示と友人関係

masters:
  -
    title: The relation between parental identity and children’s departure among middle-aged Japanese
    url: https://development.hiroshima-u.ac.jp/rese/abstract/2021_saiga.pdf
  -
    title: 不安定なアタッチメントの修正プロセスの検討―青年のメンタライジング能力・重要他者に着目して―
    url: https://development.hiroshima-u.ac.jp/rese/abstract/2021_kodera.pdf
  -
    title: 逆境的小児期体験およびアタッチメントによる情報処理プロセスの検討
    url: https://development.hiroshima-u.ac.jp/rese/abstract/2021_hashimoto.pdf
  -
    title: 青年期のアイデンティティ発達における家族の影響関係-家族関係の個別性と全体性の機能に着目して-
    url: https://development.hiroshima-u.ac.jp/rese/abstract/2020_mitou.pdf
  -
    title: 両親間葛藤のある青年の情緒的自立と適応の観点
    url: https://development.hiroshima-u.ac.jp/rese/rese/abstract/ryousin_asai2018.pdf
  - title: 両親の不和が青年の結婚不安に与える影響―親からの心理的自立を調整変数として―
  - title: 大学生における職業的アイデンティティと偶発性スキルとの関連の検討
  -
    title: 否定的アイデンティティを有する青年の特徴―測定指標の開発，社会的態度・行動との関連―
    url: https://development.hiroshima-u.ac.jp/rese/abstract/2016negativeidentity_hihara.pdf
  - title: 幼児の制裁としての攻撃に関する研究
  - title: 小中学生の怒り経験と怒り表出に関する研究
  - title: 青年期の情緒的苦痛と脆弱性の関連
  - title: 青年期のキャリア発達におけるアイデンティティ・スタイル
  - title: 大学生の関係性攻撃と対人認知
  - title: 怒りの鎮静に及ぼす影響要因の検討
  - title: 対人不安の高い者の社会的スキル評価に及ぼす不安喚起条件の影響
  - title: 大学生の職業選択への未関与におよぼす自己効力感と親や友人からのサポートの影響
  - title: 置き換えられた攻撃の誘発（TDA）の規定要因および攻撃の置き換え傾向の個人差に関する研究
  - title: 社会的比較と継時的比較に及ぼす達成目標の影響
  - title: 中学生が認知する親の発達期待と適応感との関連

doctors:
  - title: 幼児期における関係性攻撃の低減要因の検討と介入プログラムの開発
  - title: 攻撃行動に対する幼児の善悪判断
  - title: マイクロカウンセリングにおける解釈技法の有効性に関する実験的研究
  - title: 幼児に対するソーシャル教育プログラムの開発と効果検証
  - title: 青年期におけるキャリア意識の発達と関連要因の検討
  - title: やつ当たり的攻撃の規定因に関する研究
  - title: 中学生に対する集団社会的スキル訓練効果の検討